<!DOCTYPE HTML>
<html lang="zh-cn" class="sidebar-visible no-js light">

<head>
    <!-- Book generated using mdBook -->
    <meta charset="UTF-8">
    <title>错误处理 - 角落里的长生不老药</title>
    <!-- Custom HTML head -->
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#ffffff" />

    <link rel="icon" href="favicon.svg">
    <link rel="stylesheet" href="css/variables.css">
    <link rel="stylesheet" href="css/general.css">
    <link rel="stylesheet" href="css/chrome.css">
    <link rel="stylesheet" href="css/print.css" media="print">
    <!-- Fonts -->
    <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
    <link rel="stylesheet" href="fonts/fonts.css">
    <!-- Highlight.js Stylesheets -->
    <link rel="stylesheet" href="highlight.css">
    <link rel="stylesheet" href="tomorrow-night.css">
    <link rel="stylesheet" href="ayu-highlight.css">

    <!-- Custom theme stylesheets -->
    <!-- MathJax -->
    <script>
        MathJax = {
            tex: {
                inlineMath: [['$', '$'], ['\\(', '\\)']]
            }
        };
    </script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
    </script>
</head>

<body>
    <!-- Provide site root to javascript -->
    <script type="text/javascript">
        var path_to_root = "";
        var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "light";
    </script>

    <!-- Work around some values being stored in localStorage wrapped in quotes -->
    <script type="text/javascript">
        try {
            var theme = localStorage.getItem('mdbook-theme');
            var sidebar = localStorage.getItem('mdbook-sidebar');

            if (theme.startsWith('"') && theme.endsWith('"')) {
                localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
            }

            if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
            }
        } catch (e) { }
    </script>

    <!-- Set the theme before any content is loaded, prevents flash -->
    <script type="text/javascript">
        var theme;
        try { theme = localStorage.getItem('mdbook-theme'); } catch (e) { }
        if (theme === null || theme === undefined) { theme = default_theme; }
        var html = document.querySelector('html');
        html.classList.remove('no-js')
        html.classList.remove('light')
        html.classList.add(theme);
        html.classList.add('js');
    </script>

    <!-- Hide / unhide sidebar before it is displayed -->
    <script type="text/javascript">
        var html = document.querySelector('html');
        var sidebar = 'hidden';
        if (document.body.clientWidth >= 1080) {
            try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch (e) { }
            sidebar = sidebar || 'visible';
        }
        html.classList.remove('sidebar-visible');
        html.classList.add("sidebar-" + sidebar);
    </script>

    <nav id="sidebar" class="sidebar" aria-label="Table of contents">
        <div class="sidebar-scrollbox">
            <ol class="chapter"><li class="chapter-item expanded "><a href="ch01.intruction.html"><strong aria-hidden="true">1.</strong> 前言</a></li><li class="chapter-item expanded "><a href="ch02.plus_and_minus.html"><strong aria-hidden="true">2.</strong> 加和减</a></li><li class="chapter-item expanded "><a href="ch03.pattern_match.html"><strong aria-hidden="true">3.</strong> 模式匹配</a></li><li class="chapter-item expanded "><a href="ch04.parenthese.html"><strong aria-hidden="true">4.</strong> 括号</a></li><li class="chapter-item expanded "><a href="ch05.new_constructor.html"><strong aria-hidden="true">5.</strong> 定制新结构</a></li><li class="chapter-item expanded "><a href="ch06.async_programe.html"><strong aria-hidden="true">6.</strong> 异步编程</a></li><li class="chapter-item expanded "><a href="ch07.pipe.html"><strong aria-hidden="true">7.</strong> 管道操作符</a></li><li class="chapter-item expanded "><a href="ch08.error_handle.html" class="active"><strong aria-hidden="true">8.</strong> 错误处理</a></li><li class="chapter-item expanded "><a href="ch09.module.html"><strong aria-hidden="true">9.</strong> 模块</a></li><li class="chapter-item expanded "><a href="ch10.protocol_and_behaviour.html"><strong aria-hidden="true">10.</strong> 协议与行为</a></li><li class="chapter-item expanded "><a href="ch11.macro.html"><strong aria-hidden="true">11.</strong> 如何理解宏</a></li><li class="chapter-item expanded "><a href="chx.cold_knowledge.html"><strong aria-hidden="true">12.</strong> 附录 冷知识</a></li></ol>
        </div>
        <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
    </nav>

    <div id="page-wrapper" class="page-wrapper">

        <div class="page">
            <div id="menu-bar-hover-placeholder"></div>
            <div id="menu-bar" class="menu-bar sticky bordered">
                <div class="left-buttons">
                    <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents"
                        aria-label="Toggle Table of Contents" aria-controls="sidebar">
                        <i class="fa fa-bars"></i>
                    </button>
                    <button id="theme-toggle" class="icon-button" type="button" title="Change theme"
                        aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                        <i class="fa fa-paint-brush"></i>
                    </button>
                    <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                        <li role="none"><button role="menuitem" class="theme" id="light">Light (default)</button></li>
                        <li role="none"><button role="menuitem" class="theme" id="rust">Rust</button></li>
                        <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                        <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                        <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button>
                        </li>
                    </ul>
                    <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)"
                        aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S"
                        aria-controls="searchbar">
                        <i class="fa fa-search"></i>
                    </button>
                </div>

                <h1 class="menu-title">角落里的长生不老药</h1>

                <div class="right-buttons">
                    <a href="print.html" title="Print this book" aria-label="Print this book">
                        <i id="print-button" class="fa fa-print"></i>
                    </a>
                </div>
            </div>

            <div id="search-wrapper" class="hidden">
                <form id="searchbar-outer" class="searchbar-outer">
                    <input type="search" id="searchbar" name="searchbar" placeholder="Search this book ..."
                        aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                </form>
                <div id="searchresults-outer" class="searchresults-outer hidden">
                    <div id="searchresults-header" class="searchresults-header"></div>
                    <ul id="searchresults">
                    </ul>
                </div>
            </div>
            <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
            <script type="text/javascript">
                document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                Array.from(document.querySelectorAll('#sidebar a')).forEach(function (link) {
                    link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                });
            </script>

            <div id="content" class="content">
                <main>
                    <h1 id="第八章-错误处理"><a class="header" href="#第八章-错误处理">第八章 错误处理</a></h1>
<h2 id="错误分类"><a class="header" href="#错误分类">错误分类</a></h2>
<p>Erlang 中把错误分成 4 类.</p>
<ol>
<li>编译时错误, 也就是语法错误</li>
<li>逻辑错误, 漏洞或者更常见的是说法 bug.</li>
<li>运行时错误, 运行时产生的错误</li>
<li>产生的错误, 也就是写代码中故意产生的错误.</li>
</ol>
<p>前两种错误, 发生在语言之外的, 在代码层面没法对其做处理.</p>
<p>后两种错误又叫做异常. 代码层面能处理的其实都是异常.</p>
<p>异常以引发异常的机制和函数不同, 又可以分成三类:</p>
<ol>
<li>错误(<code>:error</code>), 运行时的错误, 例如 <code>1 + :a</code> 或者有 <code>:erlang.error()</code> 引发的.</li>
<li>退出(<code>:exit</code>), 由 <code>:erlang.exit/1-2-3</code> 引发, 用来使进程退出执行.</li>
<li>抛出(<code>:throw</code>), 由 <code>:erlang.throw</code> 引发.</li>
</ol>
<p>Erlang 中用 <code>catch</code> 关键字来处理这些错误.
而 Elixir 中, 除了 <code>catch</code> 外, 还从 Ruby 中引入了新的 <code>rescue</code> 保留字.
那么自然的就有一个问题, <code>catch</code> 和 <code>rescue</code> 如何分工呢?</p>
<p>按照 <a href="https://hexdocs.pm/elixir/1.13.1/Kernel.SpecialForms.html#try/1">Elixir 文档</a>
的说法, <code>rescue</code> 用来处理异常, 而 <code>catch</code> 可以用来捕获 <code>throw</code> 值和 <code>exit</code> 信号.
(The <code>rescue</code> clause is used to handle exceptions while the <code>catch</code> clause can
be used to catch thrown values and exits.)</p>
<p>但是什么是异常呢? Elixir文档中并没有明确的给出定义, 但是
<a href="https://www.erlang.org/doc/reference_manual/errors.html#exceptions">Erlang 文档</a>
中有清晰的解释.</p>
<p>如果 Elixir 中的异常和 Erlang 中的是一个概念话,
那么我对 <code>rescue</code> 和 <code>catch</code> 的分工的理解,
就成了: <code>rescue</code> 能处理所有三种类型的异常, 而 <code>catch</code> <em>只能</em> 处理 <code>throw</code> 和
<code>exit</code> 引发的异常. 但是<strong>这样的理解是错误的</strong>.</p>
<p>例如下面的代码,<code>rescue</code> 在这里并没有把我们从 <code>throw</code> 引发的错误中拯救出来.</p>
<pre><code class="language-elixir">try do
  throw(1)
rescue
  v -&gt; IO.inspect(v)
end
</code></pre>
<p>使用 Erlang 对异常的分类, <code>rescue</code> 实际上只能处理错误 <code>error</code> 类型错误.
Elixir 文档中也的确有提到 <code>rescue</code> 对 Erlang 的错误的处理,
所有的 Erlang 错误都被转化为 <code>ErlangError</code>.
这可以看作是一种暗示: Elixir 中异常对应于 Erlang 的 <code>:error</code> 类型的错误.</p>
<p>理解了这一点, 对于 <code>catch</code> 的分工描述才能有正确的理解.
在 Erlang 中, 本来就是用<code>try...catch</code> 来处理所有错误的;
Elixir 中依旧可以使用 <code>catch</code> 来处理全部的三种类型的错误, 也就是说,
在 Elixir 中 <code>catch</code> 并没有退化. 而 Elixir 中增加的保留字 <code>resuce</code>,
只是针对 <code>:error</code> 类型的处理而提供的更优雅便捷的语法.</p>
<p><strong>结论</strong>: 我起初的理解刚好搞反了, <strong><code>catch</code> 是全能的错误处理者, 而 <code>rescue</code>
才是挑剔者</strong>.</p>
<h2 id="怎么拯救"><a class="header" href="#怎么拯救">怎么拯救</a></h2>
<p>上一节我们讨论了, Elixir 中的 <code>rescue</code> 的使用场景,
现在我们来讨论如何使用它.</p>
<p>比如让我们使用 <code>try...rescue</code> 来来模拟 Erlang 的 maybe 特性.</p>
<pre><code class="language-elixir">defmodule Corner.Maybe do
  defmacro maybe(do: block) do
    quote do
      try do
        unquote(block)
      rescue
        e in [MatchError] -&gt; e.term
        # %MatchError{term: term} -&gt; term
        e -&gt; reraise e, __STACKTRACE__
      end
    end
  end
end
</code></pre>
<p>不难推测, 还可以在第 7 行的列表中加入更多的错误类型.
如果不管异常的名字叫什么都要处理的话, 就可以向第 9 行那样处理.</p>
<p>但是像第 7 行中对错误的处理, 处理的结果, 只是从错误结构中提取相应的异常消息,
那么我忍不住, 就想使用注释掉的第 8 行那样的代码.
但是第 8 行的代码是语法错误的. <code>rescue</code> 子句中, <code>-&gt;</code> 左侧的模式匹配,
只基于异常的名字来处理<sup class="footnote-reference"><a href="#rescue">1</a></sup>.</p>
<p>这样的处理有些奇怪啊! 如果允许第 8 行那样写代码, 代码不是显的更整洁吗?
为什么 Elixir 对 <code>rescue</code> 的匹配匹配语法要限制只能匹配错误名字呢?
现在还没有答案, 但是不要这一个问题阻拦了我们探索的脚步.
也许后面的探索中, 答案自然就会浮出水面呢!</p>
<div class="footnote-definition" id="rescue"><sup class="footnote-definition-label">1</sup>
<p>Elixir 文档中关于 <code>rescue</code> 匹配的文档, 翻译过来是: 除了以模式匹配外,
<code>rescue</code> 围绕异常提供了一些方便, 允许我们根据异常的名字来展开救援.
原文见 Elixir 文档关于
<a href="https://hexdocs.pm/elixir/1.13.1/Kernel.SpecialForms.html#try/1-rescue-clauses">rescue 子句的描述</a>.</p>
</div>
<h2 id="如何捕获"><a class="header" href="#如何捕获">如何捕获</a></h2>
<p>通过上面对 <code>rescue</code> 和 <code>catch</code> 的分工的讨论, 我们知道 <code>catch</code> 是三项全能.
现在让我们来看看 <code>catch</code> 的表现.</p>
<h3 id="抛接游戏"><a class="header" href="#抛接游戏">抛接游戏</a></h3>
<p>Elixir 中 <code>throw</code> 可以抛出任意的数据类型 (就像 C++ 中那样),
而 <code>catch</code> 可以原封不动的接住所有被抛出的东西.
Elixir 中没有 <code>return</code> 语句, 使用 <code>throw</code> <code>catch</code> 可以模拟它.
例如类似于下面的 Javascript 代码:</p>
<pre><code class="language-javascript">function fun(a){
  if(a &gt; 3) return &quot;a &gt; 3&quot;
  if(a &lt; 0) return &quot;a &gt; 0&quot;
  if(a == 2) return a
  return a+1
}
</code></pre>
<p>对应的 Elixir 代码可以这样来写:</p>
<pre><code class="language-elixir">def fun(a) do
  if a &gt; 3, do: throw &quot;a &gt; 3&quot;
  if a &lt; 0, do: throw &quot;a &lt; 0&quot;
  if a == 2, do: throw a
  catch
    v -&gt; v
  else
   _ -&gt; a + 1
end
</code></pre>
<h3 id="信号捕获"><a class="header" href="#信号捕获">信号捕获</a></h3>
<p>在 Erlang 中, <code>catch</code> 实际上更加类似于 Linux 进程间通信机制中的信号陷阱.
也就是说, <code>catch</code> 捕获的实际上是信号, Elixir 信号比 Linux 的信号通信高级的地方在于:
Linux 的信号种类是固定的; 而 Elixir 中 <code>exit</code> 可以发送的信号,
是由标签表示的<strong>类型</strong>与<strong>附加消息</strong>共同组成的. 其中标签个数可以认为是固定的,
但是附加信息的数量是无限的.</p>
<p><code>catch</code> 子句中完整的匹配语法是这样的:</p>
<pre><code class="language-elixir">catch
  kind, message when guard -&gt; ...
</code></pre>
<p>也就是说, <code>catch</code> 子句中 <code>-&gt;</code> 左侧, 应该是一个二元的参数列表形式.
<code>when</code> 子句是可以省略的, 就像其他环境中的 <code>when</code> 那样.
而 <code>catch v -&gt; ...</code> 是 <code>catch :throw, v -&gt; ...</code> 的语法糖,
或者按照 Erlang 文档的说法, <code>catch</code> 的默认类型是 <code>:throw</code>.</p>
<p>我们用代码来检验以下我们的理解是否正确:</p>
<pre><code class="language-elixir">1 = try do
  throw(1)
catch
  :throw, v -&gt; v
end

2.0 = try do
  throw(2.0)
catch
  v -&gt; v
end
</code></pre>
<p>对 <code>throw</code> 产生的错误来说, <code>catch v -&gt;..</code> 和 <code>catch :throw, v -&gt; ...</code> 一样.
这证实了 <code>catch v -&gt; ...</code> 只是 <code>catch :throw, v -&gt; ...</code> 的语法糖的结论.</p>
<pre><code class="language-elixir">2 =
  try do
    exit(2)
  catch
    :exit, v -&gt; v
  end
</code></pre>
<p>对 <code>exit</code> 引发的错误, 可以使用 <code>catch :exit, v -&gt;</code> 捕获.</p>
<pre><code class="language-elixir">3 =
  try do
    :erlang.error(3)
  catch
    :error, v -&gt; v
  end

:reason =
  try do
    :erlang.error(:reason, [2])
  catch
    :error, reason -&gt; reason
  end
</code></pre>
<p>对Erlang 的 <code>:erlang.error/1-2-3</code> 产生的错误, <code>catch</code> 总是能捕获其原因(代码中的变量
<code>reason</code>), 其值就是 <code>:erlang.error</code> 的第一个参数.</p>
<pre><code class="language-elixir">:badarith =
  try do
    1 / 0
  catch
    :error, v -&gt; v
  end

{:badmatch, :error} =
  try do
    :ok = :error
  catch
    # not work
    # :error, %MatchError{}=v -&gt; v
    # now `reason` is not a Error, but a tuple
    :error, reason -&gt; reason
  end
</code></pre>
<p>使用 <code>catch :error, reason -&gt; ...</code> 来捕获运行时错误,
<code>reason</code> 绑定错误发生的原因. 不同的错误, 产生的原因数据类型不统一.
比如算术计算引发的错误, 是用一个原子 <code>:badarith</code> 表示.
而匹配错误, 返回的是一个二元元组, 元组的第一个元素是原子 <code>:badmatch</code>,
第二个元素则是匹配操作符 <code>=</code> 的右操作数.</p>
<pre><code class="language-elixir">:reason =
  try do
    exit(:reason)
  catch
    :exit, v -&gt; v
  end

{:kill, 1} =
  try do
    exit({:kill, 1})
  catch
    :exit, v -&gt; v
  end
</code></pre>
<p>对于 <code>exit</code> 产生的错误, 无论传递给 <code>exit/1</code> 的是什么,
<code>catch :exit, v -&gt;</code> 语句中 <code>v</code> 都能绑定它的值.</p>
<pre><code class="language-elixir">%MatchError{} =
  try do
    raise MatchError
  catch
    :error, %MatchError{} = v -&gt; v
  end

%MatchError{} =
  try do
    raise MatchError, term: {:ok, 1}
  rescue
    v in MatchError -&gt; v
  end
</code></pre>
<p><code>catch</code> 和 <code>rescue</code> 都可以用来处理 <code>raise</code> 引发的错误.
<code>catch</code> 的语法可以更方便的使用匹配语法, <code>rescue</code> 只能匹配模块名.</p>
<p>但是, 注意对比运行时产生的匹配错误与使用 <code>raise</code> 产生的匹配错误之间的微妙区别.
运行时产生的匹配错误, 使用 <code>catch :error, v -&gt; ...</code> 语句时, <code>v</code> 绑定的是一个二元元组.
而 <code>rasie</code> 产生的错误, 表达式 <code>catch :error, v -&gt;...</code> 中 <code>v</code> 绑定的是
<code>%MatchError{}</code> 异常结构.</p>
<h2 id="更优雅的拯救"><a class="header" href="#更优雅的拯救">更优雅的拯救</a></h2>
<p>在探索 <code>catch</code> 对异常的捕获是, 我们发现 <code>catch</code> 对运行时错误和 <code>raise</code>
产生的错误有区分, 这使得 <code>catch</code> 对错误来源敏感, 这就导致了由不同的机制
(<code>error</code> 或 <code>raise</code>) 产生的相同异常 (<code>MatchError</code>), 必须使用不一致的语法来处理.
Elixir 中用 <code>rescue</code> 来统一处理异常, 而不再区分它们的来源.
可是 <code>rescue</code> 子句中的匹配的语法, 只支持对异常名匹配.
这样在需要提取异常消息的时候, 代码就不够简洁了.
好在变量可以匹配任意给定的值, 这个匹配规则没有打破.
所以 <code>rescue v -&gt;</code> 可以用来匹配任意的 <code>:error</code> 类型的异常.</p>
<p><code>rescue v -&gt; </code> 表达式中, 当变量 <code>v</code> 绑定异常结构后, 在 <code>-&gt;</code> 的右侧, 
就可以使用结构的匹配语法来对异常做匹配了.
也就是说, 对于异常, 我们可以使用下面的代码来完成匹配:</p>
<pre><code class="language-elixir">try do
   do_block_code
rescue v -&gt;
    case v do
     %ErrorName{field: field_v} -&gt; field_v
     ...
    end
...
end
</code></pre>
<p>我们可以定义自己的语法糖, 让 <code>rescue</code> 子句中, 可以使用更强大的模式匹配语法.</p>
<p><code>try</code> 是 Elixir 特殊表单, 社区对其语法有一致的预期,
为了不迷惑, 不熟悉我们的库的程序员, 我们不使用 <code>try</code> 来作为我们的宏的名字.
这个将要定义的宏是要增强 <code>rescue</code> 的匹配功能, 这里我们使用和 <code>fn!</code> 一样的命名惯例,
把我们的宏命名为<code>try!</code>.</p>
<pre><code class="language-elixir">defmodule Corner.Try do
  defmacro try!(asts) do
    Macro.postwalk(asts, &amp;walker/1)
    |&gt; make_try()
    |&gt; tap(&amp;(Macro.to_string(&amp;1) |&gt; IO.puts()))
  end
  #...
end
</code></pre>
<p>我们只是修改 <code>rescue</code> 分句, 所以, 遍历抽象语法树, 找到 <code>resuce</code> 分句相关的部分,
修改抽象语法树, 这就是 <code>try!/1</code> 最重要的工作. 这个工作有 <code>walker/1</code> 函数完成.</p>
<p><code>walker</code> 函数使用模式匹配, 识别出 <code>rescue</code> 分句, 然后调整抽象语法树对应的部分,
使得原来的 </p>
<pre><code class="language-elixir">rescue 
  %Error_1{} -&gt; ...
  %Error_2{} -&gt; ...
  ...
  %Error_n{} -&gt; ...
</code></pre>
<p>转化为:</p>
<pre><code class="language-elixir">rescue
  v -&gt; case v do
      %Error_1{} -&gt; ...
      %Error_2{} -&gt; ...
      ...
      %Error_n{} -&gt; ...
  end
</code></pre>
<p>对应的代码, 非常简单:</p>
<pre><code class="language-elixir">defp walker({:rescue, rescue_block}) do
  {:rescue,
   [
     {:-&gt;, [],
      [
        [{:v, [], nil}],
        {:case, [], [{:v, [], nil}, [do: rescue_block]]}
      ]}
   ]}
end

defp walker(ast), do: ast
</code></pre>
<p>最后, <code>try!</code> 还是需要使用特殊表达 <code>try</code> 来完成工作, 所以最后我们用 <code>make_try/1</code>
来完成对 <code>try</code> 特殊表单的调用表达式.</p>
<pre><code class="language-elixir">defp make_try(block) do
  {:try, [], [block]}
end
</code></pre>
<p>最后使用我们新定义的 <code>super_try</code> 来重构我们的 <code>maybe</code> 宏.</p>
<pre><code class="language-elixir">defmodule Corner.Maybe do
  defmacro maybe(do: block) do
    quote do
      import Corner.Super, only: [try!: 1]

      try! do
        unquote(block)
      rescue
        %MatchError{term: term} -&gt; term
      end
    end
  end

  defmacro maybe(do: block, else: else_part) do
    quote do
      import Corner.Super, only: [try!: 1]

      try! do
        unquote(block)
      rescue
        %MatchError{term: term} -&gt; term
      else
        unquote(else_part)
      end
    end
  end
end
</code></pre>
<p>测试一下:</p>
<pre><code class="language-elixir">defmodule Corner.MaybeTest do
  use ExUnit.Case
  import Corner.Maybe

  test &quot;maybe&quot; do
    result_maybe =
      maybe do
        {:ok, a} = {:ok, 2}
        {:ok, b} = {:error, a + 1}
        b + 1
      end

    assert result_maybe == {:error, 3}
  end
end
</code></pre>
<h2 id="错误处理子句的顺序"><a class="header" href="#错误处理子句的顺序">错误处理子句的顺序</a></h2>
<p>最后, 讨论一下 <code>try</code> 结构中子句的顺序. 在 Elixir 文档中, 最完整的错误处理块为
<code>try</code> ... <code>rescue</code> ... <code>catch</code> ... <code>else</code> ... <code>after</code>.
我们看到的绝大部分例子, 都是省略部分子句的情况,
但是这些子句的相对顺序还是保持的, 那么能不能改变这些子句的相对顺序呢?
比如, 把 <code>rescue</code> 放在 <code>catch</code> 后.</p>
<pre><code class="language-elixir">try do
  raise :error
catch
  v -&gt; v |&gt; IO.inspect(label: &quot;catch v&quot;)
rescue
  v -&gt; v |&gt; IO.inspect(label: &quot;rescue&quot;)
else
  v -&gt; v |&gt; IO.inspect(label: &quot;else&quot;)
after
  IO.puts(&quot;after&quot;)
end
</code></pre>
<p>上面的代码, 编译器给出的警告, 警告的内容是 <code>catch</code> 应该放在 <code>resuce</code> 的后面,
不过代码依旧可以运行. 那么为什么应该那样呢? 前面的讨论, 我们知道 <code>catch</code> 是全能捕手,
上面的代码中, 用到的是它捕获 <code>throw value</code> 的语法,
所以<code>rescue</code> 有机会捕获 <code>raise</code> 产生的错误. 但是如果使用的最通用 <code>catch</code> 的语法呢?
例如下面的代码:</p>
<pre><code class="language-elixir">catch
  :error, v -&gt; ...
rescue
  rescue_code
</code></pre>
<p>在上面的代码中, <code>rescue</code> 子句就是死代码, 永远不用有机会执行. 编译器给出警告的原因.</p>
<p>那么除了 <code>rescue</code> 和 <code>catch</code> 的相对位置外, 其他的子句呢? 能改变顺序码?
比如, 把 <code>after</code> 子句放在 <code>resuce</code> 前面, 可以吗?</p>
<pre><code class="language-elixir">try do
  1 / 0
after
  IO.puts(&quot;after&quot;)
rescue
  v -&gt;
    v |&gt; IO.inspect(label: &quot;rescue&quot;)
    :rescue
catch
  v -&gt;
    v |&gt; IO.inspect(label: &quot;catch&quot;)
    :catch
else
  v -&gt; v |&gt; IO.inspect(label: &quot;else&quot;)
end
</code></pre>
<p>上面的代码片段, 不但能顺利通过编译, 而且警告都没有. 也就是说, 这是完全合法的代码.
<code>after</code> 在代码中出现的顺序, 不影响其功能. 进一步的, 不难推测,
<code>else</code> 也可以放在 <code>resuce</code> 子句前.</p>
<pre><code class="language-elixir">try do
  2
rescue
  v -&gt; IO.inspect(v, label: &quot;resuce v&quot;)
else
  v -&gt; v |&gt; IO.inspect(label: &quot;else&quot;)
catch
  :error, v -&gt;
    IO.inspect(v, label: &quot;catch :error ,v&quot;)
end
</code></pre>
<p>上面的代码, 也一切正常.</p>
<p>总结一下: 在 <code>try</code> 子句中: 如果 <code>rescue</code> 和 <code>catch</code> 都存在的话,
<code>rescue</code> 应该放在 <code>catch</code> 子句的前面, 而其他的子句的顺序并没有特别的要求.</p>
<p>最后提醒读者, 我们这里是对语法规则的探索, 才故意打乱其顺序的,
绝对不是鼓励大家在实际的编码中也这样做.</p>
<h2 id="什么时候必须-try"><a class="header" href="#什么时候必须-try">什么时候必须 try</a></h2>
<p>在 Elixir 的官方文档中, 我们看到可以省略 <code>try</code> 关键字, 而直接处理错误的例子.
例如在命名函数中:</p>
<pre><code class="language-elixir">def fun() do
   ...
catch
  :error, v -&gt; v
after
  ...
end
</code></pre>
<p>那么什么时候, 可以省略 <code>try</code> 呢? 是不是所有后面需要 <code>do-block</code> 的语法结构中,
都可以使用省略 <code>try</code> 而直接使用错误处理子句呢? 不是的. 例如,
我们就不可以给 <code>if</code> 语句加一个 <code>catch</code> 子句. 就像下面的代码这样.</p>
<pre><code class="language-elixir">if 3 &lt; 4 do
  1 -&gt; 1 / 0
catch
  :error, _ -&gt; &quot;1/0&quot;
else
  &quot;how it can be 3 not less than 4&quot;
end
</code></pre>
<p>我们看到命名函数中, 可以直接使用错误处理的子句, 那么是不是在匿名函数中也可以直接使用呢?
答案也是否定的, 而且 Elixir ≪语法参考≫文档的
<a href="https://hexdocs.pm/elixir/1.13.1/syntax-reference.html#reserved-words">≪保留字≫</a>
小节也给出了提示:</p>
<blockquote>
<p><code>do</code>, <code>end</code>, <code>catch</code>, <code>rescue</code>, <code>after</code>, <code>else</code> 在 <code>do-end</code> 块中使用.</p>
</blockquote>
<p><code>fn</code> 的语法是这样的:</p>
<pre><code class="language-elixir">fn a -&gt; ... end
</code></pre>
<p>当这里的 <code>...</code> 表示多于一个表达式的时候, 这里实际上是一个暗含的块, 但是并不是一个
<code>do-block</code>. 这一点我们可以通过 <code>quote</code> 语句, 在抽象语法树的层面上看清.</p>
<pre><code class="language-elixir">quote do
  fn a -&gt;
    a + 1
    a - 1
  end

  def f(a) do
    a + 1
    a - 1
  end
end
</code></pre>
<p><code>fn</code> 的块结构抽象语法树是:</p>
<pre><code class="language-elixir">{:__block__, [],
  [
    {:+, [context: Elixir, import: Kernel], [{:a, [], Elixir}, 1]},
    {:-, [context: Elixir, import: Kernel], [{:a, [], Elixir}, 1]}
  ]}
</code></pre>
<p>而函数 <code>f(a)</code> 定义的 <code>do...end</code> 块的抽象语法树是:</p>
<pre><code class="language-elixir">[do: {:__block__, [],
  [
    {:+, [context: Elixir, import: Kernel], [{:a, [], Elixir}, 1]},
    {:-, [context: Elixir, import: Kernel], [{:a, [], Elixir}, 1]}
  ]}]
</code></pre>
<p>知道了这些知识, 就不难理解为什么 <code>fn</code> 定义匿名函数的时候, <code>try</code> 不能省略了.</p>
<p>接着探索会发现, <code>def/2</code>, <code>defp/2</code>, <code>defmacro/2</code> 和 <code>defmacrop</code> 中可以省略 <code>try</code>.
其他情形下对 <code>try</code> 的省略,  都是对这个特定规则的过度推广.</p>

                </main>

                <nav class="nav-wrapper" aria-label="Page navigation">
                    <!-- Mobile navigation buttons -->
                    <a rel="prev" href="ch07.pipe.html" class="mobile-nav-chapters previous"
                        title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a rel="next" href="ch09.module.html" class="mobile-nav-chapters next"
                        title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
                    <div style="clear: both"></div>
                </nav>
            </div>
        </div>

        <nav class="nav-wide-wrapper" aria-label="Page navigation">
            <a rel="prev" href="ch07.pipe.html" class="nav-chapters previous" title="Previous chapter"
                aria-label="Previous chapter" aria-keyshortcuts="Left">
                <i class="fa fa-angle-left"></i>
            </a>
            <a rel="next" href="ch09.module.html" class="nav-chapters next" title="Next chapter"
                aria-label="Next chapter" aria-keyshortcuts="Right">
                <i class="fa fa-angle-right"></i>
            </a>
        </nav>

    </div>

    <script type="text/javascript">
        window.playground_copyable = true;
    </script>
    <script src="elasticlunr.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="mark.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="searcher.js" type="text/javascript" charset="utf-8"></script>
    <script src="clipboard.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="highlight.js" type="text/javascript" charset="utf-8"></script>
    <script src="book.js" type="text/javascript" charset="utf-8"></script>

    <!-- Custom JS scripts -->
</body>

</html>